# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "stackprof", "~> 0.2.27"

gem "algorithm", "~> 0.0.0"

gem "algorithms", "~> 1.0"

gem "ruby-lsp", "~> 0.23.14", :group => :development
